### ISSUE TITLE
configurable saml_sp_prefix for sub-domains. 

### ISSUE THREAD

**Issue by sagarjauhari** [toyokazu/rack-saml#15]
Is there a way to configure `saml_sp_prefix`? Since it is generated using on the request, it is not possible to use it in different subdomains.

**Comment by toyokazu** [comment]
Sorry to be late response. Thank you for updating the status. Have you resolved the problem by yourself? Have you tried to edit configuration file? If possible, could you write down the solution? It will help the people facing the same problem :)

Best Regards

**Comment by sagarjauhari** [comment]
This adds a comment for how to deal with subdomains https://github.com/toyokazu/rack-saml/pull/17
